"""
printnc.py

Description:
    The purpose of this prorgam is to print netCDF metadata to
    `sys.stdout`.

Usage: 
    python printnc.py <nc_path>

Example:
    ```sh
    $ python src/lib/printnc.py /Users/williamchuter-davies/Downloads/WFEL/ESA/CEDA\ Archive/ESA\ Lakes\ Climate\ Change\ Initiative\ \(Lakes_cci\)\ Lake\ products,\ Version\ 3.0/merged_product/2023/ESACCI-LAKES-L3S-LK_PRODUCTS-MERGED-20230101-fv3.0.0.nc
    <class 'netCDF4.Dataset'>
    root group (NETCDF4 data model, file format HDF5):
        title: ESA Lakes_cci product
        institution: LWL: Laboratoire d'Etudes en Geophysique et Oceanographie Spatiales, Collecte Localisation Satellites; LWE: Laboratoire d'Etudes en Geophysique et Oceanographie Spatiales, Collecte Localisation Satellites; LSWT: University of Reading; LIC: H2O Geomatics; LWLR: Plymouth Marine Laboratory LSC: Collecte Localisation Satellites;
        source: LWL: European Space Agency (ESA), National Aeronautics and Space Administration (NASA), European Organisation for the Exploitation of Meteorological Satellites (EUMETSAT), National Oceanic and Atmospheric Administration (NOAA), Indian Space Research Organisation (ISRO); LWE: European Space Agency (ESA), National Aeronautics and Space Administration (NASA); LSWT: European Space Agency (ESA), European Organisation for the Exploitation of Meteorological Satellites (EUMETSAT), European Centre for Medium-Range Weather Forecasts (ECMWF) LIC: European Space Agency (ESA), National Aeronautics and Space Administration (NASA); LWLR: Calimnos processor by Plymouth Marine Laboratory, including calls to Idepix (SNAP) and POLYMER (Hygeos) algorithms; LSC: European Space Agency (ESA), National Aeronautics and Space Administration (NASA), European Organisation for the Exploitation of Meteorological Satellites (EUMETSAT), National Oceanic and Atmospheric Administration (NOAA);
        history: LWL:  Generated by Laboratoire d'Etudes en Geophysique et Oceanographie Spatiales, Collecte Localisation Satellites; LWE:  Generated by Laboratoire d'Etudes en Geophysique et Oceanographie Spatiales, Collecte Localisation Satellites; LSWT: created with collate_10DAYS_onMASK_RES120_new_unc.py; LIC:  Lake ice cover processor by H2O Geomatics; LWLR: Calimnos processor by Plymouth Marine Laboratory, including calls to Idepix (SNAP) and POLYMER (Hygeos) algorithms LSC:  Lake storage change processor by CLS;
        references: https://climate.esa.int/en/projects/lakes/
        ...
        geospatial_lon_resolution: 0.008333333
        doi: 10.5285/a56dba09df8a42ec9fba8b8c7a5e1f69
        dimensions(sizes): time(1), lat(21600), lon(43200), nv(2)
        variables(dimensions): int64 time(time), float32 lat(lat), float32 lon(lon), float32 chla(time, lat, lon), float32 tsm(time, lat, lon), float32 acdom440(time, lat, lon), float32 Kd490(time, lat, lon), float32 Kd560(time, lat, lon), float32 Kd665(time, lat, lon), float32 KdPAR(time, lat, lon), float32 phycocyanin(time, lat, lon), float32 Rw400(time, lat, lon), float32 Rw412(time, lat, lon), float32 Rw443(time, lat, lon), float32 Rw469(time, lat, lon), float32 Rw490(time, lat, lon), float32 Rw510(time, lat, lon), float32 Rw531(time, lat, lon), float32 Rw547(time, lat, lon), float32 Rw560(time, lat, lon), float32 Rw620(time, lat, lon), float32 Rw645(time, lat, lon), float32 Rw665(time, lat, lon), float32 Rw674(time, lat, lon), float32 Rw681(time, lat, lon), float32 Rw709(time, lat, lon), float32 Rw754(time, lat, lon), float32 Rw779(time, lat, lon), float32 Rw859(time, lat, lon), float32 Rw885(time, lat, lon), float32 Rw900(time, lat, lon), float32 Rw1020(time, lat, lon), float32 chla_uncertainty(time, lat, lon), float32 tsm_uncertainty(time, lat, lon), float32 acdom440_uncertainty(time, lat, lon), float32 Rw400_uncertainty_bias(time, lat, lon), float32 Rw412_uncertainty_bias(time, lat, lon), float32 Rw443_uncertainty_bias(time, lat, lon), float32 Rw469_uncertainty_bias(time, lat, lon), float32 Rw490_uncertainty_bias(time, lat, lon), float32 Rw510_uncertainty_bias(time, lat, lon), float32 Rw531_uncertainty_bias(time, lat, lon), float32 Rw547_uncertainty_bias(time, lat, lon), float32 Rw560_uncertainty_bias(time, lat, lon), float32 Rw620_uncertainty_bias(time, lat, lon), float32 Rw645_uncertainty_bias(time, lat, lon), float32 Rw665_uncertainty_bias(time, lat, lon), float32 Rw674_uncertainty_bias(time, lat, lon), float32 Rw681_uncertainty_bias(time, lat, lon), float32 Rw709_uncertainty_bias(time, lat, lon), float32 Rw754_uncertainty_bias(time, lat, lon), float32 Rw779_uncertainty_bias(time, lat, lon), float32 Rw859_uncertainty_bias(time, lat, lon), float32 Rw885_uncertainty_bias(time, lat, lon), float32 Rw900_uncertainty_bias(time, lat, lon), float32 Rw1020_uncertainty_bias(time, lat, lon), float32 Rw400_uncertainty_rmsd(time, lat, lon), float32 Rw412_uncertainty_rmsd(time, lat, lon), float32 Rw443_uncertainty_rmsd(time, lat, lon), float32 Rw469_uncertainty_rmsd(time, lat, lon), float32 Rw490_uncertainty_rmsd(time, lat, lon), float32 Rw510_uncertainty_rmsd(time, lat, lon), float32 Rw531_uncertainty_rmsd(time, lat, lon), float32 Rw547_uncertainty_rmsd(time, lat, lon), float32 Rw560_uncertainty_rmsd(time, lat, lon), float32 Rw620_uncertainty_rmsd(time, lat, lon), float32 Rw645_uncertainty_rmsd(time, lat, lon), float32 Rw665_uncertainty_rmsd(time, lat, lon), float32 Rw674_uncertainty_rmsd(time, lat, lon), float32 Rw681_uncertainty_rmsd(time, lat, lon), float32 Rw709_uncertainty_rmsd(time, lat, lon), float32 Rw754_uncertainty_rmsd(time, lat, lon), float32 Rw779_uncertainty_rmsd(time, lat, lon), float32 Rw859_uncertainty_rmsd(time, lat, lon), float32 Rw885_uncertainty_rmsd(time, lat, lon), float32 Rw900_uncertainty_rmsd(time, lat, lon), float32 Rw1020_uncertainty_rmsd(time, lat, lon), uint16 lwlr_quality_flags(time, lat, lon), float32 lat_bounds(lat, nv), float32 lon_bounds(lon, nv), float64 time_bounds(time, nv), uint8 lake_cover_class(time, lat, lon), uint8 lic_process_flag(time, lat, lon), uint8 lic_class_agreement(time, lat, lon), uint8 lic_modis_overlap(time, lat, lon), float64 lic_rf_total_uncertainty(time, lat, lon), uint8 lic_rf_quality_level(time, lat, lon), float64 fractional_ice_cover(time, lat, lon), float64 lic_total_cloud_cover(time, lat, lon), float64 ice_cover_area(time, lat, lon), int16 lake_surface_water_temperature(time, lat, lon), int16 lswt_uncertainty(time, lat, lon), int8 lswt_quality_level(time, lat, lon), float64 water_surface_height_above_reference_datum(time, lat, lon), int16 lwl_uncertainty(time, lat, lon), int8 lwl_quality_flag(time, lat, lon), float64 lake_surface_water_extent(time, lat, lon), int16 lwe_uncertainty(time, lat, lon), int8 lwe_quality_flag(time, lat, lon), float64 lake_storage_change(time, lat, lon), int8 lsc_quality_flag(time, lat, lon), int32 crs()
        groups:
```

Written by William Chuter-Davies
"""

# Standard Library Imports
import sys

from pathlib import Path

# Third-Party Imports
from netCDF4 import Dataset

# Read `sys.argv[1]` into `nc_path`
nc_path = Path(sys.argv[1])

# Assert `nc_path.exists()`
assert nc_path.exists()

# Read `nc_path` into Dataset
rootgrp  = Dataset(nc_path)

# Print Dataset
print(rootgrp)

# Close Dataset
rootgrp.close()