r"""
print_nc.py

Description:
    The purpose of this prorgam is to print netCDF metadata to
    `sys.stdout`.

Usage: 
    python print_nc.py <nc_path>

Example:
    ```sh
    $ python src/lib/print_nc.py /Users/williamchuter-davies/Downloads/WFEL/ESA/CEDA\ Archive/ESA\ Lakes\ Climate\ Change\ Initiative\ \(Lakes_cci\)\ Lake\ products,\ Version\ 3.0/merged_product/2023/ESACCI-LAKES-L3S-LK_PRODUCTS-MERGED-20230101-fv3.0.0.nc
    <xarray.Dataset> Size: 384GB
    Dimensions:                                     (time: 1, lat: 21600,
                                                    lon: 43200, nv: 2)
    Coordinates:
    * time                                        (time) datetime64[ns] 8B 2023...
    * lat                                         (lat) float32 86kB -90.0 ... ...
    * lon                                         (lon) float32 173kB -180.0 .....
    Dimensions without coordinates: nv
    Data variables: (12/99)
        chla                                        (time, lat, lon) float32 4GB ...
        tsm                                         (time, lat, lon) float32 4GB ...
        acdom440                                    (time, lat, lon) float32 4GB ...
        Kd490                                       (time, lat, lon) float32 4GB ...
        Kd560                                       (time, lat, lon) float32 4GB ...
        Kd665                                       (time, lat, lon) float32 4GB ...
        ...                                          ...
        lake_surface_water_extent                   (time, lat, lon) float64 7GB ...
        lwe_uncertainty                             (time, lat, lon) float32 4GB ...
        lwe_quality_flag                            (time, lat, lon) float32 4GB ...
        lake_storage_change                         (time, lat, lon) float64 7GB ...
        lsc_quality_flag                            (time, lat, lon) float32 4GB ...
        crs                                         int32 4B ...
    Attributes: (12/42)
        title:                      ESA Lakes_cci product
        institution:                LWL: Laboratoire d'Etudes en Geophysique et O...
        source:                     LWL: European Space Agency (ESA), National Ae...
        history:                    LWL:  Generated by Laboratoire d'Etudes en Ge...
        references:                 https://climate.esa.int/en/projects/lakes/
        tracking_id:                ee1263b3-d599-46cb-9e19-9601a9c32476
        ...                         ...
        key_variables:              lake_water_level, lake_ water_extent, lake_ic...
        geospatial_lat_units:       degrees_north
        geospatial_lon_units:       degrees_east
        geospatial_lat_resolution:  0.008333333
        geospatial_lon_resolution:  0.008333333
        doi:                        10.5285/a56dba09df8a42ec9fba8b8c7a5e1f69
```

Written by William Chuter-Davies
"""


# Standard Library Imports
import pathlib
import sys

# Related Third-party Imports
import xarray

# Local Application/Library Specific Imports
from lib.io.vars import RETURN_SUCCESS, RETURN_FAILURE


def main() -> int:
    # If argument count is not equal to 2, return with `RETURN_FAILURE`
    if len(sys.argv) != 2:
        print(f'fatal: unexpected argument count: {sys.argv}')
        
        return RETURN_FAILURE
    
	# Read `sys.argv[1]` into `nc_path`
    nc_path = pathlib.Path(sys.argv[1])

    # If `nc_path` does not exist, return with `RETURN_FAILURE`
    if not nc_path.exists():
        print(f'fatal: no such file or directory: {sys.argv[1]}')

        return RETURN_FAILURE
    
    # Attempt to ...
    try:
        # Open Dataset specified by `nc_path`
        with xarray.open_dataset(nc_path) as ds:
            # Print `xds` to `sys.stdout`
            print(ds)
    # On exception, return with `RETURN_FAILURE`
    except Exception as e:
        print(f'fatal: exception: {e}')
        
        return RETURN_FAILURE

    return RETURN_SUCCESS


if __name__ == '__main__':
    sys.exit(main())